name: Build Kernel A06B

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Cài môi trường build
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib \
          gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev \
          lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev \
          libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush \
          rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
          unzip python3 python2 xz-utils

    - name: Tải toolchain Google Clang
      run: |
        mkdir -p toolchain
        cd toolchain
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r450784d.tar.gz
        tar -xvf clang-r450784d.tar.gz
        cd ..

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH=$PWD/toolchain/bin:$PATH
        make a06x_00_defconfig
        make -j$(nproc) CC=clang CROSS_COMPILE=aarch64-linux-gnu-

    - name: Đóng gói AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3
        cp arch/arm64/boot/Image* AnyKernel3/ || true
        cd AnyKernel3
        zip -r9 Kernel-A06B.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Kernel-A06B
        path: AnyKernel3/Kernel-A06B.zip
