name: Build Kernel A06B (KernelSU + SUSFS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y bc bison build-essential curl flex libssl-dev unzip xz-utils zip

    - name: Download Clang toolchain
      run: |
        mkdir -p $HOME/toolchains/clang-r450784e
        wget -O clang-r450784e.tar.gz https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/clang-r450784e.tar.gz
        tar -xzf clang-r450784e.tar.gz -C $HOME/toolchains/clang-r450784e

    - name: Download ARM GNU Toolchain
      run: |
        mkdir -p $HOME/toolchains/gcc
        wget -O gcc-toolchain.tar.xz https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        tar -xf gcc-toolchain.tar.xz -C $HOME/toolchains/gcc

    - name: Set toolchain PATH
      run: |
        echo "$HOME/toolchains/clang-r450784e/bin" >> $GITHUB_PATH
        echo "$HOME/toolchains/gcc/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu/bin" >> $GITHUB_PATH

    - name: Clone KernelSU Next + SUSFS
      run: |
        git clone https://github.com/KernelSU-Next/KernelSU-Next.git ksu-next
        git clone https://gitlab.com/simonpunk/susfs4ksu.git susfs
        cp -r ksu-next/* drivers/kernelsu/
        cp -r susfs/kernel-5.15/kernel_patches/* .

    - name: Build kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        make a06x_00_defconfig
        make -j$(nproc) CC=clang CROSS_COMPILE=aarch64-none-linux-gnu-

    - name: Package AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3
        cp arch/arm64/boot/Image* AnyKernel3/
        cd AnyKernel3 && zip -r9 Kernel-A06B-KSU-SUSFS.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Kernel-A06B-KSU-SUSFS
        path: AnyKernel3/Kernel-A06B-KSU-SUSFS.zip
