name: Build Kernel

on:
  workflow_dispatch:   # Cho phép bấm nút chạy tay
  push:                # Tự chạy khi push code mới
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: sudo apt update && sudo apt install -y \
        git curl wget unzip bc bison build-essential flex \
        gcc g++ clang lld llvm make cpio python3 python3-pip \
        libssl-dev libelf-dev libncurses-dev zstd

    - name: Run build script
      run: bash build_kernel.sh
