name: Build Samsung A06B Kernel (KernelSU Next + SUSFS with AnyKernel3)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget curl bc bison build-essential flex \
          libssl-dev libncurses5-dev xz-utils zip unzip cpio python3 \
          liblz4-tool

    - name: Download Clang and ARM GNU toolchains
      run: |
        mkdir -p $HOME/toolchains
        wget -O clang.tar.gz https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/clang-r450784e.tar.gz
        mkdir -p $HOME/toolchains/clang && tar -xzf clang.tar.gz -C $HOME/toolchains/clang
        wget -O gcc.tar.xz https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        mkdir -p $HOME/toolchains/gcc && tar -xJf gcc.tar.xz -C $HOME/toolchains/gcc
        echo "$HOME/toolchains/clang/bin" >> $GITHUB_PATH
        echo "$HOME/toolchains/gcc/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu/bin" >> $GITHUB_PATH

    - name: Apply KernelSU Next + SUSFS patches
      run: |
        git clone https://github.com/KernelSU-Next/KernelSU-Next.git ksu-next
        git clone https://gitlab.com/simonpunk/susfs4ksu.git susfs
        cp -r ksu-next/* drivers/kernelsu/ || true
        cp -r susfs/kernel-5.15/kernel_patches/* . || true

    - name: Build kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CC=clang
        export CROSS_COMPILE=aarch64-none-linux-gnu-
        make a06x_00_defconfig
        make -j$(nproc) Image.gz

    - name: Package with AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3 AnyKernel3
        cp arch/arm64/boot/Image* AnyKernel3/ || true
        cp arch/arm64/boot/dts/*.dtb AnyKernel3/ || true
        cp arch/arm64/boot/dts/*.dtbo AnyKernel3/ || true
        # Tuỳ chỉnh anykernel.sh nếu muốn (ví dụ tên kernel)
        cd AnyKernel3
        zip -r9 Kernel-A06B-KSU-SUSFS.zip *

    - name: Upload the flashable kernel zip
      uses: actions/upload-artifact@v3
      with:
        name: Kernel-A06B-KSU-SUSFS
        path: AnyKernel3/Kernel-A06B-KSU-SUSFS.zip
